# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:

- task: UiPathInstallPlatform@6
  inputs:
    cliVersion: 'Windows.25.10.7'
    
- task: UiPathPack@6
  inputs:
    projectJsonPath: 'project.json'
    versionType: 'AutoVersion'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'
    outputType: 'Tests'
    orchestratorConnection: 'AzureDev'
    traceLevel: 'None'


- task: UiPathDeploy@6
  inputs:
    orchestratorConnection: 'AzureDev'
    packagesPath: '$(Build.ArtifactStagingDirectory)\Output'
    folderName: 'Kavina'
    traceLevel: 'None'

- task: UiPathTest@6
  inputs:
    testTarget: 'TestSet'
    orchestratorConnection: 'AzureDev'
    testSet: 'AzureTestSet'
    folderName: 'Kavina'
    traceLevel: 'None'